export const STOCK_MOVEMENT_TYPES = {
  PURCHASE: "PURCHASE",
  SALE: "SALE",

  TRANSFER_OUT: "TRANSFER_OUT",
  TRANSFER_IN: "TRANSFER_IN",

  TRANSFER_MISMATCH_IN: "TRANSFER_MISMATCH_IN",
  TRANSFER_ADJUSTMENT: "TRANSFER_ADJUSTMENT",

  STOCK_ADJUSTMENT: "STOCK_ADJUSTMENT",
};
