export const COLLECTIONS = {
  USERS: "users",
  COUNTERS: "counters",
  BRANCHES: "branches",
  CATEGORIES: "categories",
  PRODUCTS: "products",
  VARIANTS: "product_variants",
  CUSTOMERS: "customers",
  EMPLOYEES: "employees",
  CUSTOMER_BRANCHES: "customer_branches",
  SUPPLIERS: "suppliers",
  PURCHASES: "purchases",
  PURCHASE_RETURNS: "purchase_returns",
  STOCKS: "stocks",
  SALES: "sales",
  STOCK_LEDGERS: "stock_ledgers",
  SALE_ITEMS: "sale_items",
  SALE_PAYMENTS: "sale_payments",
  TRANSACTIONS: "transactions",
  SUPPLIER_LEDGER: "supplier_ledger",
  ATTENDANCES: "attendances",
  AUDIT_LOGS: "audit_logs",
  LEDGERS: "ledgers",
  TAX_CONFIGS: "tax_configs",
};
