export const COLLECTIONS = {
  USERS: "users",
  COUNTERS: "counters",
  BRANCHES: "branches",
  CUSTOMERS: "customers",
  CUSTOMER_BRANCHES: "customer_branches",
  SUPPLIERS: "suppliers",
  CATEGORIES: "categories",
  PRODUCTS: "products",
  VARIANTS: "product_variants",
  PURCHASES: "purchases",
  STOCKS: "stocks",
  SALES: "sales",
  TRANSACTIONS: "transactions",
};
